//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLKPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registration()
        {
            this.details = new HashSet<detail>();
        }

        public int SlNo { get; set; }

        [Required(ErrorMessage = "Please Provide Username", AllowEmptyStrings = false)]

        public string UserName { get; set; }

        [Required(ErrorMessage = "Please provide Email ID", AllowEmptyStrings = false)]

        [DataType(DataType.EmailAddress)]

        public string EmailId { get; set; }

        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]

        [DataType(DataType.Password)]

        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password Mismatch, Please try again")]

        [DataType(DataType.Password)]

        public string ConfirmPassword { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail> details { get; set; }
    }
}
